language: node_js
node_js:
- '5'
- '4'
notifications:
  email:
    on_failure: change
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
    node: '5'
https://github:
  com/postcss/postcss:
    com:
      secure: odTrF10C/lAdRtsucF4qCSsFCxcSwJJSaOd2p+N5yPcrJ67+RrmDYiVgl4AqSdBIIDWHMUuIJ29M5OtsboGRtd8+q95ims9zy78DqQ0eTmg4aYmm+z/IUy6Z90Z2QgRjJVmwAuKC6S1Y7MzxTq0EDon4TIpktsU8rg5XWYesH5naDnhNV3PhpFWMZ9Cp9a87hQZA+rgs/QlxzgYrhDa7vt/+iC9j+2Pm3t9TV6/ruWhJOo8ZExfGKzaZtUhVmeYc2HivfYOFQfgClP3ZYO3QygHZuekcuJ+X8VpbEwoMssZzTFr50Sg8uwAbK+eWEPdeXbrzSc9MOLph4F4+GRNx8oGfBLzKDrF2jn+L3CQ+lOTXoD4W6dkBsklLdcpAGEDtc4l81pDJ5sZCrJwCtZOcXMZNOXKyJysrH+dtJOY/H11+1942AOUfu0WzJISoXi89be+YNJxvAe30ZhkCLhzgljHCuzjwp8LGw1c+Nz+bNHjzIED+V3XAizqzHibr7479Q71twFxNPkIpW7TbgCCRvaoGhT8TCVcYF0WOF6fG35Zbyr2whyI2Z8t8mWgQgGYwEQ7GalhtD6vI/hrkFKOTNsvfU6fgsxUqu0wHLe+WENu7eQx4exkUndlk7sQxHbWzVpZKFNHGJqD+a5NnK0btVCuNu3KP/ERb26DESFhmkLQ=
